### ISSUE TITLE
pkt_dts_time

### ISSUE THREAD

**Issue by atitoff** [InB4DevOps/bitrate-viewer#1]
Change in code pkt_pts_time to pkt_dts_time!

**Comment by InB4DevOps** [comment]
Hey,
Why do you suggest to make this change?

**Comment by atitoff** [comment]
Because errors occur

![image](https://user-images.githubusercontent.com/13304485/139490856-f991a831-5189-43f8-b2bd-0ef9bb9b69d9.png)

**Comment by CrypticSignal** [comment]
The issue is that `pkt_pts_time` doesn't exist in te XML file. The PTS values are labelled as `pts_time` rather than `pkt_pts_time`. There are two solutions:
1. Change `frame.get('pkt_pts_time')` on line 38 to `frame.get('pts_time')`
2. Use the decoding timestamps (`pkt_dts_time`) instead. I had a quick chat with @slhck and I was told that is the relevant metric in terms of downloading/streaming:

> "You always download frames in DTS order because that's the order the decoder needs it. That's how the segments are structured. The decoder can then output the frames in display order.
> 
> So for all things streaming-related it would make sense to look at things in DTS order.
> 
> As for the packet size it's one packet per DTS, they all come in DTS order. You'll notice when you use ffprobe to show packets vs frames, the first will be in DTS order and the latter in PTS order (because frames will already be decoded by then)"

Therefore, personally, I would go for solution 2.

**Comment by atitoff** [comment]
I use latest version ffprobe `ffprobe version 2021-10-28-git-e84c83ef98-essentials_build-www.gyan.dev`

![image](https://user-images.githubusercontent.com/13304485/139532953-63fb3061-1043-499a-9f0d-4069626a217b.png)

**Comment by CrypticSignal** [comment]
> I use latest version ffprobe `ffprobe version 2021-10-28-git-e84c83ef98-essentials_build-www.gyan.dev`
> 
> ![image](https://user-images.githubusercontent.com/13304485/139532953-63fb3061-1043-499a-9f0d-4069626a217b.png)

What's your point? I already explained what the issue is. Your version of ffprobe also shows the presentation timestamps (`pts`/`pts_time`). The reason this program was giving an error is because it was looking for `pkt_pts_time` instead of `pts` or `pts_time`.

**Comment by InB4DevOps** [comment]
I don't know why you don't have pkt_pts_time in your output files because i have it (also with the lastest version 4.41)

![image](https://user-images.githubusercontent.com/73686890/139554905-a89818de-9c6b-4bd9-8492-6806acaad2b6.png)

Anyway, please pull again to get a fix for the problem
@atitoff please let me know if this fixes your issue.
